FROM node:14.17.4-alpine3.14

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apk update
RUN apk add --no-cache \
    git \
    curl \
    libpng-dev \
    oniguruma-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    shadow

# Create system user 
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www/front

#Config Entrypoint
COPY docker-images/node/entrypoints/entrypoint-front.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

EXPOSE 3000

