ARG PHP_VERSION
FROM php:${PHP_VERSION}

ARG workDir
ARG dirApp
ARG entrypoint
ARG supervisordDir

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    libssl-dev \ 
    libc-client-dev \
    libkrb5-dev  \
    supervisor

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

#Install extension

#Redis
RUN pecl install redis\
    && docker-php-ext-enable redis 
# Mongo + mailparse
RUN pecl install mongodb mailparse && \
    docker-php-ext-enable mongodb mailparse   
#imap
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
    docker-php-ext-install soap imap zip gd bcmath pcntl

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR $workDir

# Copy custom configurations PHP
COPY docker/php/custom.ini /usr/local/etc/php/conf.d/custom.ini

# composer install
RUN cd ${workDir}
COPY --chown=www-data:www-data ${dirApp} .
RUN rm -rf vendor
RUN composer update --no-interaction

#Config Supervisor
COPY ${supervisordDir} /etc/supervisor/conf.d/supervisord.conf
COPY ${supervisordDir} /etc/supervisord.d/

#Config Entrypoint
COPY ${entrypoint} /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
